
/* ----------------------- ¦—¦— ---------------------- */

#define CUST_NUM 1
#define CUST_NAME 2
#define CUST_ZIP 3
#define CUST_TEL 4
#define CUST_ADDR 5
#define CUST_CAR 6
#define CUST_CODE 7
#define CUST_YEAR 8
#define CUST_FROM 9
#define CUST_TO 10
#define CUST_MONEY 11
#define CUST_FROM2 12
#define CUST_TO2 13
#define CUST_PERSON0 14
#define CUST_PERSON1 15
#define CUST_PERSON2 16
#define CUST_PERSON3 17
#define CUST_PERSON4 18
#define CUST_THING0 19
#define CUST_THING1 20
#define CUST_THING2 21
#define CUST_THING3 22
#define CUST_THING4 23
#define CUST_LOSS0 24
#define CUST_LOSS1 25
#define CUST_LOSS2 26
#define CUST_LOSS3 27
#define CUST_LOSS4 28
#define CUST_CAR0 29
#define CUST_CAR1 30
#define CUST_CAR2 31
#define CUST_CAR3 32
#define CUST_CAR4 33
#define CUST_TOTAL 34
#define CUST_NUM2 35
#define CUST_NAME2 36
#define CUST_TOTALINS 37
#define CUST_DRIVE 38
#define SAVE_NUM 39
#define SAVE_NAME 40
#define SAVE_ZIP 41
#define SAVE_TEL 42
#define SAVE_ADDR 43
#define SAVE_WORK 44
#define SAVE_DAY 45
#define SAVE_TERM 46
#define SAVE_MONEY 47

#define CUSTOMER 0
#define INSTSAVE 1

