/* ----------------------- £¥·qµe ---------------------- */

#define PROF_NAME 1
#define PROF_MAJOR 2
#define PROF_SCH 3
#define PROF_STATUS 4
#define PROF_ZIP1 5
#define PROF_ADDR1 6
#define PROF_AREA1 7
#define PROF_TEL1 8
#define PROF_ZIP2 9
#define PROF_ADDR2 10
#define PROF_AREA2 11
#define PROF_TEL2 12
#define PROF_MEMO 13
#define GROUP_NAME 14
#define GROUP_PRESI 15
#define GROUP_ZIP 16
#define GROUP_ADDR 17
#define GROUP_AREA 18
#define GROUP_TEL 19
#define GROUP_MEMO 20
#define MEDIA_NAME 21
#define MEDIA_PART 22
#define MEDIA_PERSON 23
#define MEDIA_ZIP 24
#define MEDIA_ADDR 25
#define MEDIA_AREA 26
#define MEDIA_TEL 27
#define MEDIA_FAX 28
#define MEDIA_MEMO 29
#define SUPPORT_NAME 30
#define SUPPORT_PART 31
#define SUPPORT_JOB 32
#define SUPPORT_INVI 33
#define SUPPORT_ZIP 34
#define SUPPORT_ADDR 35
#define SUPPORT_AREA 36
#define SUPPORT_TEL 37
#define SUPPORT_MEMO 38
#define CAMP_NAME 39
#define CAMP_NO 40
#define CAMP_HAK 41
#define CAMP_SOSOK 42
#define CAMP_MAJOR 43
#define CAMP_ZIP 44
#define CAMP_ADDR 45
#define CAMP_AREA 46
#define CAMP_TEL 47
#define CAMP_MEMO 48

#define PROF 0
#define GROUP 1
#define MEDIA 2
#define SUPPORT 3
#define CAMP 4

